"""make changes for attendance

Revision ID: bedd6b1b1c51
Revises: a2b4b537e6a9
Create Date: 2026-03-10 11:09:31.882500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedd6b1b1c51'
down_revision: Union[str, Sequence[str], None] = 'a2b4b537e6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'attendance_date', name='uq_attendance_student_subject_date')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_class_id'), 'attendance_records', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_subject_id'), 'attendance_records', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_teacher_id'), 'attendance_records', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_teacher_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_subject_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_class_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
