"""updating test columns

Revision ID: d39fb32025ea
Revises: 98f90c23496e
Create Date: 2026-02-15 18:55:19.683800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39fb32025ea'
down_revision: Union[str, Sequence[str], None] = '98f90c23496e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_notes', sa.Column('content', sa.String(), nullable=False))
    op.alter_column('generated_notes', 'subject',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('generated_notes', 'chapter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('generated_notes', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_generated_notes_id'), 'generated_notes', ['id'], unique=False)
    op.drop_column('generated_notes', 'pdf_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_notes', sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_generated_notes_id'), table_name='generated_notes')
    op.alter_column('generated_notes', 'difficulty',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('generated_notes', 'chapter',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('generated_notes', 'subject',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('generated_notes', 'content')
    # ### end Alembic commands ###
