"""updated schema

Revision ID: f787174b0829
Revises: fd3fcbde73e7
Create Date: 2026-02-11 11:53:13.114191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f787174b0829'
down_revision: Union[str, Sequence[str], None] = 'fd3fcbde73e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('is_student_generated', sa.Boolean(), nullable=True),
    sa.Column('is_teacher_provided', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_notes')
    # ### end Alembic commands ###
