"""update test answer table

Revision ID: fd8e54fc8929
Revises: d39fb32025ea
Create Date: 2026-02-18 09:38:20.028360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8e54fc8929'
down_revision: Union[str, Sequence[str], None] = 'd39fb32025ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('question_id', sa.Integer(), nullable=False))
    op.drop_column('test_answers', 'question_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('test_answers', 'question_id')
    # ### end Alembic commands ###
